services:
  sispo-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sispo-backend
    restart: unless-stopped
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - APP_NAME=SISPO
      - APP_ENV=${APP_ENV:-production}
      - APP_KEY=${APP_KEY:-base64:CqLKMbVAwp88J+O8Ijccpx6g+DhmBduQJc6pycMzwYg=}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_URL=${APP_URL:-https://api.sispo.unitepc.pro}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-th-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-sispo_db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root_th_seguro2026}
      - DB_CORE_HOST=${DB_CORE_HOST:-th-mysql}
      - DB_CORE_PORT=${DB_CORE_PORT:-3306}
      - DB_CORE_DATABASE=${DB_CORE_DATABASE:-sigeth_db}
      - DB_CORE_USERNAME=${DB_CORE_USERNAME:-root}
      - DB_CORE_PASSWORD=${DB_CORE_PASSWORD:-root_th_seguro2026}
      - SANCTUM_STATEFUL_DOMAINS=postulaciones.unitepc.pro,api.sispo.unitepc.pro,sigeth.unitepc.pro
    volumes:
      - sispo_storage:/var/www/html/storage
      - /var/www:/host_www:ro
    networks:
      - th-ecosystem

volumes:
  sispo_storage:

networks:
  th-ecosystem:
    external: true
